apiVersion: v1
kind: Service
metadata:
  name: clinica-redis
  labels:
    run: clinica-redis
spec:
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    app: clinica-redis
